'use client';

import React from 'react';
import { cn } from '@/src/lib/utils';
import { useLocalization } from '@/src/context/localization';
import { reportCardStyles as s } from './monthly-report-card.styles';

const ReportFooter: React.FC = () => {
  const { t } = useLocalization();

  return (
    <div className={cn(s.footer, 'report-card-footer')}>
      <p className={cn(s.footerBrand, 'report-card-footer-brand')}>{t('Generated by Sprout Track')}</p>
    </div>
  );
};

export default ReportFooter;
