export const adminSideNavStyles = {
  container: "fixed inset-y-0 left-0 z-50 flex flex-col bg-white transform transition-all duration-300 ease-in-out w-64",
  containerNonModal: "flex flex-col bg-white w-64 min-h-screen h-full transition-all duration-300 ease-in-out",
  containerOpen: "translate-x-0",
  containerClosed: "-translate-x-full",
  overlay: "fixed inset-0 bg-black/30 z-40 transition-opacity duration-300",
  overlayOpen: "opacity-100",
  overlayClosed: "opacity-0 pointer-events-none",
  header: "flex items-center justify-between px-4 border-gray-200",
  logo: "w-10 h-10 object-contain",
  appName: "text-lg font-semibold text-teal-700",
  closeButton: "text-gray-500 hover:text-gray-700 transition-colors duration-200",
  navItems: "flex-1 py-4 px-4 overflow-y-auto",
  navItem: "flex items-center w-full px-4 py-3 text-gray-700 hover:bg-teal-50 hover:text-teal-700 transition-colors duration-200 rounded-lg mb-2",
  navItemActive: "bg-teal-50 text-teal-700 font-medium",
  navItemIcon: "mr-3 h-5 w-5",
  navItemLabel: "text-sm",
  footer: "border-t border-gray-200 p-4",
  footerButton: "flex items-center w-full px-4 py-3 text-gray-700 hover:bg-teal-50 hover:text-teal-700 transition-colors duration-200 rounded-lg mb-2",
  footerButtonIcon: "mr-3 h-5 w-5",
  footerButtonLabel: "text-sm",
};
