export const chatThreadListStyles = {
  container: "flex flex-col h-full min-h-0 bg-gray-50/80",
  header: "px-4 py-3 flex items-center justify-between border-b border-slate-200 flex-shrink-0",
  headerTitle: "text-sm font-semibold text-gray-900",
  toggleButton: "w-7 h-7 rounded-lg flex items-center justify-center transition-all duration-150 cursor-pointer border-none",
  toggleButtonActive: "bg-slate-200",
  toggleButtonInactive: "bg-transparent hover:bg-slate-100",
  searchContainer: "px-3 py-2 border-b border-slate-200 flex-shrink-0",
  searchInput: "w-full px-3 py-1.5 text-xs border border-slate-200 rounded-lg bg-white focus:border-emerald-300 focus:ring-1 focus:ring-emerald-100 outline-none placeholder-gray-400",
  list: "flex-1 min-h-0 overflow-y-auto",
  threadItem: "px-4 py-3 cursor-pointer border-b border-slate-100 transition-all duration-100 border-l-[3px]",
  threadItemActive: "bg-white border-l-emerald-500",
  threadItemInactive: "bg-transparent border-l-transparent hover:bg-white/60",
  threadSubject: "text-[13px] text-gray-900 truncate flex-1",
  threadSubjectUnread: "font-semibold",
  threadSubjectRead: "font-normal",
  unreadDot: "w-2 h-2 rounded-full bg-emerald-500 flex-shrink-0",
  threadMeta: "flex items-center justify-between text-[11px] text-gray-500",
  threadMetaLeft: "truncate",
  threadMetaRight: "flex-shrink-0 text-gray-400",
  emptyState: "flex flex-col items-center justify-center py-12 text-gray-400 text-sm gap-2",
} as const;
